$(document).ready(function(){
    $("#arc").ready(function(){
        $(".arc").hide();
    });
     $("#com").ready(function(){
        $(".com").hide();
    });
    $("#eve").ready(function(){
        $(".eve").hide();
    });
    $("#evet").ready(function(){
        $(".evet").hide();
    });
    $("#wel").ready(function(){
        $(".wel").hide();
    });
});